# Generated by Django 4.1.5 on 2023-02-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0002_rename_company_id_employee_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_email',
            field=models.EmailField(blank=True, db_column='company_email', max_length=256, null=True),
        ),
    ]
